spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/test_db_dev?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true